[package]
name = "spelling-bee"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
flate2 = "1.0.26"
miniz_oxide = "0.7.1"
regex = "1.8.1"
winapi = "0.3.9"
xz2 = "0.1.7"
